config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, path: 'gonderi'

  scope(path_names: { new: 'yeni', edit: 'duzenle' }) do
    resources :categories, path: 'kategori'
  end
  
  root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user

    def word_count
        self.body.split.size
    end

    def reading_time
        (word_count / 180.0).ceil
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end
    
    def show
        @category = Category.find(params[:id])
    end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = current_user.categories.build(category_params)
        if @category.save
            redirect_to new_post_path
        else
            render plain: "hata"
            render 'new'
        end
    end
    
    def destroy
        @category = Category.find(params[:id])
        if @category.destroy
            flash[:success] = "Başarıyla Silindi"
            redirect_to categories_path
        else
            flash[:danger] = "Başarısız"
        end
    end
    
    private
    
    def category_params
        params.require(:category).permit(:title, :user_id)
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            redirect_to posts_path
        else
            flash[:danger] = "Bir hata oluştu"
            render 'new'
        end
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            flash[:success] = "#{@post.title} Güncellendi."
            redirect_to post_path
        else
            render 'edit'
            flash[:danger] = "Başarısız"
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        if @post.destroy
            flash[:success] = "Silindi!"
            redirect_to posts_path
        else
            flash[:danger] = "Başarısız"
        end
    end

    private
        def post_params
            params.require(:post).permit(:title, :body, :category_id)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/markas_helper.rb
module MarkasHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_with scope: :category, model: @category, class:"eight columns offset-by-two" do |form| %>
    <%= form.label :title%>
    <%= form.text_field :title, type:"text", class:"u-full-width", placeholder:"Başlık Giriniz", required: 'true' %>
    <div class="btn-center">
        <%= form.submit "Kaydet", class:"btn btn-primary-outline" %>
    </div>
<% end %>

app/views/categories/index.html.erb
<h1>Tüm Kategoriler</h1>

<% @categories.each do |category| %>
    <p>
        <%= link_to category.title, category %>, 
        <%= link_to "delete", category, method: :delete,
                                  data: { confirm: "Emin misin? Bu işlem geri alınamaz!" }%>
    </p>
    
<% end %>

app/views/categories/new.html.erb
<h1 class="header">Yeni Kategori</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>
<h1><%= @category.user.email %></h1>
<p>
    <% @category.posts.each do |post| %>
        <%= link_to post.title, post %>
    <% end %>
</p>

app/views/layouts/_menu.html.erb
<nav class="navbar">
  <div class="container">
    <ul class="navbar-list">
      <li class="navbar-item">
        <a class="navbar-link" href="/">Anasayfa</a>
      </li>
      <li class="navbar-item">
        <%= link_to  "Yeni Yazı", new_post_path, class:"navbar-link" %>
      </li>
      <li class="navbar-item">
        <a class="navbar-link" href="#examples">Examples</a>
      </li>
      <li class="navbar-item">
        <a class="navbar-link" href="#" data-popover="#moreNavPopover">More</a>
      </li>
    </ul>
    <ul class="navbar-list sag">
      <% if user_signed_in? %>
        <li class="navbar-item">
          <%= link_to 'Çıkış Yap', destroy_user_session_path, method: :delete, class: "navbar-link" %>
        </li>
      <% else %>
        <li class="navbar-item">
          <%= link_to 'Giriş Yap', new_user_session_path, class: "navbar-link" %>
        </li>
        <li class="navbar-item">
          <%= link_to 'Kayıt Ol', new_user_registration_path, class: "navbar-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/menu' %>
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        
        <%= yield %>
        <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with scope: :post, class:"eight columns offset-by-two", model: @post do |form| %>
        <%= form.label :title%>
        <%= form.text_field :title, type:"text", class:"u-full-width", placeholder:"Başlık Giriniz", required: 'true' %>
        <%= form.label :body %>
        <%= form.text_area :body, class:"u-full-width", rows:"8", required: 'true' %>
        <%= link_to  "Kategori Ekle", new_category_path, class:'btn link' %>
        <%= form.select :category_id, 
                        Category.all.collect{ |category| [category.title, category.id] },
                        { include_blank: "Bir Kategori Seçiniz..." },
                        class:"u-full-width", required: 'true' %>
        <div class="btn-center">
            <%= form.submit "Kaydet", class:"btn btn-primary-outline" %>
        </div>
<% end %>

app/views/posts/edit.html.erb
<h1 class="header"><%= @post.title %> Yazısını Güncelle</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1 class="header">Tüm Yazılar</h1>

<div class="row">
  <% @posts.each do |post| %>
    <div class="docs-section">
      <div class="nine columns">
        <h6><%= link_to post.title, post, class:'docs-header' %></h6>
        <p><%= truncate( post.body, length: 37, omission: "...#{post.body[-5, 5]}") %></p>
      </div>
      <div class="three columns sag">
        <div class="wordcount">
          <i class="fa fa-clock-o"></i>
          <span><%= pluralize(post.reading_time, 'minute')%></span><br>
          <%= time_ago_in_words(post.created_at) %> önce
        </div>
        <% if user_signed_in? %>
          <%= link_to edit_post_path(post), class:'button button-icon' do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to post_path(post),
                                      data: {:confirm => 'Are you sure?'},
                                      method: :delete,
                                      class:'button button-icon' do %>
            <i class="fa fa-remove"></i>
          <% end %>
        <% end %>
      </div>
      <div class="u-cf">
        
        <div class="post-info">
          <p><%= link_to post.category.title, post.category, class:"btn " %> Kategorisinde, <%= post.user.email %> tarafından Yazıldı</p>
        </div>
      </div> 
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="header">Yeni Gönderi</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1 class="header"><%= @post.title %></h1>
<p><%= @post.body %></p>
<p><% if !@post.user.nil? %><%= @post.user.email %><% end %></p>